version: '3.8'

services:
  user-service:
    image: userservice:latest
    ports:
      - "8080:8080"
    networks:
      - my_network

  account-service:
    image: accountservice:latest
    ports:
      - "8081:8081"
    networks:
      - my_network

  payment-service:
    image: paymentservice:latest
    ports:
      - "8082:8082"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge